# Лабораторная работа 7. Разработка единого шаблона предварительной обработки данных

## Подключение библиотек

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Загрузка данных и разделение на матрицу признаков и зависимую переменную

In [ ]:
dataset = pd.read_csv('imports-85.data')
dataset.head()

symboling  normalized-losses         make fuel-type aspiration  \
0          3                123  alfa-romero       gas        std   
1          3                123  alfa-romero       gas        std   
2          1                123  alfa-romero       gas        std   
3          2                164         audi       gas        std   
4          2                164         audi       gas        std   

  num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0          two  convertible          rwd           front        88.6  ...   
1          two  convertible          rwd           front        88.6  ...   
2          two    hatchback          rwd           front        94.5  ...   
3         four        sedan          fwd           front        99.8  ...   
4         four        sedan          4wd           front        99.4  ...   

   engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0          130         mpfi  3.47    2.68               9.0        111   
1          130         mpfi  3.47    2.68               9.0        111   
2          152         mpfi  2.68    3.47               9.0        154   
3          109         mpfi  3.19    3.40              10.0        102   
4          136         mpfi  3.19    3.40               8.0        115   

   peak-rpm city-mpg  highway-mpg  price  
0      5000       21           27  13495  
1      5000       21           27  16500  
2      5000       19           26  16500  
3      5500       24           30  13950  
4      5500       18           22  17450  

[5 rows x 26 columns]

In [ ]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values
print ("Матрица признаков"); print(X)
print ("Зависимая переменная"); print(y)

Матрица признаков
[[3 123 'alfa-romero' ... 5000 21 27]
 [3 123 'alfa-romero' ... 5000 21 27]
 [1 123 'alfa-romero' ... 5000 19 26]
 ...
 [-1 95 'volvo' ... 5500 18 23]
 [-1 95 'volvo' ... 4800 26 27]
 [-1 95 'volvo' ... 5400 19 25]]
Зависимая переменная
['gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas'
 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas'
 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas'
 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas'
 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas'
 'gas' 'gas' 'gas' 'diesel' 'gas' 'gas' 'diesel' 'diesel' 'diesel'
 'diesel' 'diesel' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas'
 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'diesel'
 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas' 'gas'
 'gas' 'gas' 'gas' 'gas' 'gas' 'diesel' 'gas' 'diesel' 'gas' 'diesel'
 'gas' 'diesel' 'gas' 'dies

### 3. Обработка пропущенных значений

In [ ]:
# Новая версия класса-трансформера, предыдущая Imputer - устарела
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'most_frequent')
imputer = imputer.fit(X[:, 1:3])
X_without_nan = X.copy()
X_without_nan[:, 1:3] = imputer.transform(X[:, 1:3])
X_without_nan

array([[3, 123, 'alfa-romero', ..., 5000, 21, 27],
       [3, 123, 'alfa-romero', ..., 5000, 21, 27],
       [1, 123, 'alfa-romero', ..., 5000, 19, 26],
       ...,
       [-1, 95, 'volvo', ..., 5500, 18, 23],
       [-1, 95, 'volvo', ..., 4800, 26, 27],
       [-1, 95, 'volvo', ..., 5400, 19, 25]], dtype=object)

### 4. Обработка категориальных данных

#### 4.1 Замена категории кодом (LabelEncoder)

In [ ]:
from sklearn.preprocessing import LabelEncoder
y = dataset['fuel-type']

labelencoder_y = LabelEncoder()

print("Зависимая переменная до обработки")

print(y.unique())

y = labelencoder_y.fit_transform(y)

print("Зависимая переменная после обработки")

print(y)

Зависимая переменная до обработки
['gas' 'diesel']
Зависимая переменная после обработки
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 0 0 0 0 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0
 1 0 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 0
 1 1 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1]


#### 4.2 Применение OneHotEncoder

In [ ]:
# создаем копию "грязного" объекта: спропусками и некодированными категориями
X_dirty = dataset[['make', 'fuel-type', 'highway-mpg', 'price']]
X_dirty

make fuel-type  highway-mpg  price
0    alfa-romero       gas           27  13495
1    alfa-romero       gas           27  16500
2    alfa-romero       gas           26  16500
3           audi       gas           30  13950
4           audi       gas           22  17450
..           ...       ...          ...    ...
200        volvo       gas           28  16845
201        volvo       gas           25  19045
202        volvo       gas           23  21485
203        volvo    diesel           27  22470
204        volvo       gas           25  22625

[205 rows x 4 columns]

In [ ]:
# Список трансформеров

transformers = [
    ('onehot', OneHotEncoder(sparse_output=False), ['make', 'fuel-type']),  # Применяем OneHotEncoder к категориальным столбцам month и day
    ('imp_num', SimpleImputer(strategy='mean'), ['highway-mpg', 'price']),  # Применяем SimpleImputer с mean к числовым столбцам FFMC и DMC
]


# Создаем объект ColumnTransformer и передаем ему список трансформеров
ct = ColumnTransformer(transformers, remainder='passthrough', verbose_feature_names_out=False)

# Выполняем трансформацию признаков
X_transformed = ct.fit_transform(X_dirty)

# Выводим результаты трансформации
print(X_transformed.shape)
print(X_transformed)

(205, 26)
[[1.0000e+00 0.0000e+00 0.0000e+00 ... 1.0000e+00 2.7000e+01 1.3495e+04]
 [1.0000e+00 0.0000e+00 0.0000e+00 ... 1.0000e+00 2.7000e+01 1.6500e+04]
 [1.0000e+00 0.0000e+00 0.0000e+00 ... 1.0000e+00 2.6000e+01 1.6500e+04]
 ...
 [0.0000e+00 0.0000e+00 0.0000e+00 ... 1.0000e+00 2.3000e+01 2.1485e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 ... 0.0000e+00 2.7000e+01 2.2470e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 ... 1.0000e+00 2.5000e+01 2.2625e+04]]


In [ ]:
# Можно преобразовать полученный многомерный массив обратно в Dataframe
new_columns = ct.get_feature_names_out()
X_data = pd.DataFrame(X_transformed, columns=new_columns)
print(X_data)

     make_alfa-romero  make_audi  make_bmw  make_chevrolet  make_dodge  \
0                 1.0        0.0       0.0             0.0         0.0   
1                 1.0        0.0       0.0             0.0         0.0   
2                 1.0        0.0       0.0             0.0         0.0   
3                 0.0        1.0       0.0             0.0         0.0   
4                 0.0        1.0       0.0             0.0         0.0   
..                ...        ...       ...             ...         ...   
200               0.0        0.0       0.0             0.0         0.0   
201               0.0        0.0       0.0             0.0         0.0   
202               0.0        0.0       0.0             0.0         0.0   
203               0.0        0.0       0.0             0.0         0.0   
204               0.0        0.0       0.0             0.0         0.0   

     make_honda  make_isuzu  make_jaguar  make_mazda  make_mercedes-benz  ...  \
0           0.0         0.0   