# Лабораторная работа 7. Разработка единого шаблона предварительной обработки данных

## Подключение библиотек

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Загрузка данных и разделение на матрицу признаков и зависимую переменную

In [ ]:
dataset = pd.read_csv('forestfires.csv')
dataset.head()

X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

In [ ]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values
print ("Матрица признаков"); print(X)
print ("Зависимая переменная"); print(y)

Матрица признаков
[[7 5 'mar' ... 51 6.7 0.0]
 [7 4 'oct' ... 33 0.9 0.0]
 [7 4 'oct' ... 33 1.3 0.0]
 ...
 [7 4 'aug' ... 70 6.7 0.0]
 [1 4 'aug' ... 42 4.0 0.0]
 [6 3 'nov' ... 31 4.5 0.0]]
Зависимая переменная
['fri' 'tue' 'sat' 'fri' 'sun' 'sun' 'mon' 'mon' 'tue' 'sat' 'sat' 'sat'
 'fri' 'mon' 'wed' 'fri' 'sat' 'mon' 'wed' 'sat' 'tue' 'mon' 'sun' 'sat'
 'sat' 'sun' 'fri' 'mon' 'sat' 'sun' 'fri' 'mon' 'fri' 'sun' 'mon' 'tue'
 'tue' 'fri' 'sat' 'tue' 'tue' 'sat' 'tue' 'sat' 'wed' 'wed' 'mon' 'mon'
 'mon' 'mon' 'thu' 'sun' 'wed' 'wed' 'thu' 'thu' 'tue' 'sun' 'mon' 'fri'
 'sun' 'sun' 'thu' 'sun' 'mon' 'thu' 'fri' 'fri' 'fri' 'fri' 'fri' 'fri'
 'fri' 'tue' 'fri' 'thu' 'fri' 'mon' 'fri' 'tue' 'sun' 'sun' 'tue' 'wed'
 'thu' 'thu' 'thu' 'thu' 'sun' 'sat' 'sat' 'fri' 'sun' 'sun' 'mon' 'sun'
 'sat' 'sat' 'sun' 'sun' 'sun' 'tue' 'tue' 'sat' 'sat' 'fri' 'thu' 'sun'
 'sat' 'mon' 'fri' 'fri' 'sun' 'mon' 'tue' 'tue' 'sat' 'sat' 'mon' 'thu'
 'mon' 'mon' 'sun' 'tue' 'fri' 'sun' 'mon' 'fri' 'wed' 's

### 3. Обработка пропущенных значений

In [ ]:
# Новая версия класса-трансформера, предыдущая Imputer - устарела
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'most_frequent')
imputer = imputer.fit(X[:, 1:3])
X_without_nan = X.copy()
X_without_nan[:, 1:3] = imputer.transform(X[:, 1:3])
X_without_nan

array([[7, 5, 'mar', ..., 51, 6.7, 0.0],
       [7, 4, 'oct', ..., 33, 0.9, 0.0],
       [7, 4, 'oct', ..., 33, 1.3, 0.0],
       ...,
       [7, 4, 'aug', ..., 70, 6.7, 0.0],
       [1, 4, 'aug', ..., 42, 4.0, 0.0],
       [6, 3, 'nov', ..., 31, 4.5, 0.0]], dtype=object)

### 4. Обработка категориальных данных

#### 4.1 Замена категории кодом (LabelEncoder)

In [ ]:
from sklearn.preprocessing import LabelEncoder
y = dataset['day']

labelencoder_y = LabelEncoder()

print("Зависимая переменная до обработки")

print(y.unique())

y = labelencoder_y.fit_transform(y)

print("Зависимая переменная после обработки")

print(y)

Зависимая переменная до обработки
['fri' 'tue' 'sat' 'sun' 'mon' 'wed' 'thu']
Зависимая переменная после обработки
[0 5 2 0 3 3 1 1 5 2 2 2 0 1 6 0 2 1 6 2 5 1 3 2 2 3 0 1 2 3 0 1 0 3 1 5 5
 0 2 5 5 2 5 2 6 6 1 1 1 1 4 3 6 6 4 4 5 3 1 0 3 3 4 3 1 4 0 0 0 0 0 0 0 5
 0 4 0 1 0 5 3 3 5 6 4 4 4 4 3 2 2 0 3 3 1 3 2 2 3 3 3 5 5 2 2 0 4 3 2 1 0
 0 3 1 5 5 2 2 1 4 1 1 3 5 0 3 1 0 6 3 2 1 3 4 5 2 3 1 5 5 1 6 0 2 6 4 1 5
 5 4 0 3 2 0 2 3 2 6 6 0 1 4 2 2 3 4 6 6 0 4 6 6 3 1 2 2 4 3 6 5 3 1 3 1 0
 5 3 1 2 3 0 4 5 6 5 0 4 4 5 1 5 3 3 6 2 4 2 5 0 4 2 2 0 1 2 2 3 1 6 1 3 0
 1 0 6 3 1 2 3 2 6 3 5 5 2 3 2 5 2 3 6 0 3 3 3 3 3 6 6 6 6 6 6 4 4 4 2 2 2
 2 1 0 0 0 0 5 5 5 5 5 5 5 5 3 6 4 1 1 1 1 0 5 3 6 0 3 6 2 2 2 2 2 0 5 5 3
 3 3 6 2 1 1 0 0 2 3 3 3 3 3 3 3 3 6 6 6 4 4 4 4 4 4 4 4 4 2 2 2 2 2 2 2 2
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 5 5 5 5 5 2 3
 3 6 3 4 0 2 1 2 4 3 6 4 6 4 2 3 3 4 0 0 1 0 3 5 1 3 3 3 2 6 6 4 0 4 6 5 2
 2 0 5 0 0 1 2 3 4 5 6 3 3 6 6 3 2 2 4 4 1 4 3 4 2 4 3 0 2 1

#### 4.2 Применение OneHotEncoder

In [ ]:
# создаем копию "грязного" объекта: спропусками и некодированными категориями
X_dirty = dataset[['month', 'day', 'FFMC', 'DMC']]
X_dirty

month  day  FFMC    DMC
0     mar  fri  86.2   26.2
1     oct  tue  90.6   35.4
2     oct  sat  90.6   43.7
3     mar  fri  91.7   33.3
4     mar  sun  89.3   51.3
..    ...  ...   ...    ...
512   aug  sun  81.6   56.7
513   aug  sun  81.6   56.7
514   aug  sun  81.6   56.7
515   aug  sat  94.4  146.0
516   nov  tue  79.5    3.0

[517 rows x 4 columns]

In [ ]:
# Список трансформеров

transformers = [
    ('onehot', OneHotEncoder(sparse_output=False), ['month', 'day']),  # Применяем OneHotEncoder к категориальным столбцам month и day
    ('imp_num', SimpleImputer(strategy='mean'), ['FFMC', 'DMC']),  # Применяем SimpleImputer с mean к числовым столбцам FFMC и DMC
]


# Создаем объект ColumnTransformer и передаем ему список трансформеров
ct = ColumnTransformer(transformers, remainder='passthrough', verbose_feature_names_out=False)

# Выполняем трансформацию признаков
X_transformed = ct.fit_transform(X_dirty)

# Выводим результаты трансформации
print(X_transformed.shape)
print(X_transformed)

(517, 21)
[[  0.    0.    0.  ...   0.   86.2  26.2]
 [  0.    0.    0.  ...   0.   90.6  35.4]
 [  0.    0.    0.  ...   0.   90.6  43.7]
 ...
 [  0.    1.    0.  ...   0.   81.6  56.7]
 [  0.    1.    0.  ...   0.   94.4 146. ]
 [  0.    0.    0.  ...   0.   79.5   3. ]]


In [ ]:
# Можно преобразовать полученный многомерный массив обратно в Dataframe
new_columns = ct.get_feature_names_out()
X_data = pd.DataFrame(X_transformed, columns=new_columns)
print(X_data)

     month_apr  month_aug  month_dec  month_feb  month_jan  month_jul  \
0          0.0        0.0        0.0        0.0        0.0        0.0   
1          0.0        0.0        0.0        0.0        0.0        0.0   
2          0.0        0.0        0.0        0.0        0.0        0.0   
3          0.0        0.0        0.0        0.0        0.0        0.0   
4          0.0        0.0        0.0        0.0        0.0        0.0   
..         ...        ...        ...        ...        ...        ...   
512        0.0        1.0        0.0        0.0        0.0        0.0   
513        0.0        1.0        0.0        0.0        0.0        0.0   
514        0.0        1.0        0.0        0.0        0.0        0.0   
515        0.0        1.0        0.0        0.0        0.0        0.0   
516        0.0        0.0        0.0        0.0        0.0        0.0   

     month_jun  month_mar  month_may  month_nov  ...  month_sep  day_fri  \
0          0.0        1.0        0.0        0.0